# Provider Configuration
# Generated by CARL for SOC 2 Type II

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      ManagedBy   = "CARL"
      Compliance  = "SOC 2 Type II"
      Environment = var.environment
    }
  }
}

# US-East-1 provider (required for global services like CloudFront, WAF global)
provider "aws" {
  alias  = "us_east_1"
  region = "us-east-1"

  default_tags {
    tags = {
      ManagedBy   = "CARL"
      Compliance  = "SOC 2 Type II"
      Environment = var.environment
    }
  }
}