# Remediation for: VPC Flow Logs Not Enabled: vpc-0945e283bd2eb3364
# Finding ID: finding-42c34c071699
# Resource: AWS::EC2::VPC - arn:aws:ec2:us-east-1:403802364021:vpc/vpc-0945e283bd2eb3364
# Risk Level: MEDIUM
# Generated by CARL at 2026-07-17T18:26:49.693440
# Requested by: U015Z3ARQCF


resource "aws_flow_log" "vpc_0945e283bd2eb3364_flow_log" {
  iam_role_arn    = aws_iam_role.flowlogs.arn
  log_destination = aws_cloudwatch_log_group.vpc_flowlogs.arn
  traffic_type    = "ALL"
  vpc_id          = "vpc-0945e283bd2eb3364"
}

resource "aws_cloudwatch_log_group" "vpc_flowlogs" {
  name              = "/aws/vpc/flowlogs/vpc-0945e283bd2eb3364"
  retention_in_days = 30
}

resource "aws_iam_role" "flowlogs" {
  name = "vpc-flowlogs-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = {
        Service = "vpc-flow-logs.amazonaws.com"
      }
      Action = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy" "flowlogs" {
  name = "vpc-flowlogs-policy"
  role = aws_iam_role.flowlogs.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "logs:DescribeLogGroups",
        "logs:DescribeLogStreams"
      ]
      Resource = "*"
    }]
  })
}

